# Generated by Django 4.2.25 on 2025-11-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Общий XP'),
        ),
    ]
