# Generated by Django 4.2.25 on 2025-11-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_profile_total_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень'),
        ),
    ]
